[package]
name = "keynotes"
version = "0.1.0"
edition = "2018"

[lib]
name = "keynotes"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

home = "0.5.3"
